### ISSUE TITLE
Call to pretty printer fails

### ISSUE THREAD

**Issue by ytzemih** [xahlee/xah-wolfram-mode#6]
Hi Xah, thanks for this very nice WolframScript integration. 

It seems as if the .el has a mistake on line 76 leading to an error when pressing TAB-TAB.
Should the call to xah-get-bounds-of-block be  a call to xah-wolfram-get-bounds-of-block?

Thanks, 
Mario

**Comment by xahlee** [comment]
thank you. fixed in https://github.com/xahlee/xah-wolfram-mode/commit/5cbe8d65d9afd0c40f11da57808463e14aca0bd6

**Comment by ytzemih** [comment]
Great, thanks!
