### ISSUE TITLE
Improved interaction with WolframScript engine

### ISSUE THREAD

**Issue by ytzemih** [xahlee/xah-wolfram-mode#7]
Dear Xah, 

I wonder whether the call of WolframScript could be turned into a non-blocking call? That would make it easier to deal with long-running scripts.

Also, for large scripts, is there a way to execute just one line or a region? (Major modes for R, Julia, and Octave support that and I found that quite convenient.) 

Thanks a lot for a nice tool, 
Mario

**Comment by xahlee** [comment]
i'll try to do the non-blocking. may have complications.

one line execute is nice feature. i'll try to implement that too.

**Comment by ytzemih** [comment]
I see, I don't know about the richness of the API/interface of wolframscript. Only knowing from julia-mode, ESS, octave-mode that they keep an extra terminal open, e.g. with Julia REPL running, such that emacs can feed inputs through some channel. Perhaps, STDIN? julia-mode has a include, region, and line execution modes, which streamlines working with it. Hope that helps.

**Comment by xahlee** [comment]
xah-wolfram-run-script now async, major fix bug. thanks to ytzemih.
commit 5cbe8d6

**Comment by xahlee** [comment]
now there's xah-wolfram-eval-current-line too.

**Comment by ytzemih** [comment]
Thanks, @xahlee, this is great.
